version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${FB_PORT}:8080"
    volumes:
      - "${DOCKER_STATIC_HOSTING}:/data"
      - "./config:/config"
    environment:
      FB_BASEURL: "/filebrowser"
      VIRTUAL_PORT: ${FB_PORT}
